[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simtwo"
version = "1.0.0"
description = "..."
readme = "README.md"
requires-python = ">=3.12,<3.15"
license = {file = "LICENSE"}
authors = [{name = "Brett Martin"}]

# TODO: Verify that this works later. Not sure which of these belong here (or if I should have used "==" for any of them)
dependencies = [
    "sequence>=0.8.4",
    "imgui[glfw]>=2.0.0",
    "glfw>=2.10.0",
    "PyOpenGL>=3.1.10",
    "PyOpenGL-accelerate>=3.1.10",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "keras>=3.14.1",
    "customtkinter>=5.2.2",
    "matplotlib>=3.10.8",
    "qutip>=5.2.2",
    "numpy>=2.4.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
